vich_uploader:
    db_driver: orm

    mappings:
        pet_image:
            uri_prefix: /images/pets
            upload_destination: '%kernel.project_dir%/public/images/pets'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
