home:
    path: /
    controller: App\Controller\PortalController::home

features:
    path: /features
    controller: App\Controller\PortalController::features

feature:
    path: /feature/{id}
    controller: App\Controller\PortalController::feature

about:
    path: /about
    controller: App\Controller\PortalController::about

user :
    path: /user/{id}
    controller: App\Controller\PortalController::createUser